server:
  port: 9091

tnt:
  shipmentsUrl: http://localhost:9090/shipments?
  trackUrl: http://localhost:9090/track?
  pricingUrl: http://localhost:9090/pricing?
  connectTimeout: 2000
  readTimeout: 2000

tnttaskexecutor:
  corepoolsize: 4
  maxpoolsize:  8
  queuecapacity: 5


myRunnerEnabled: true
  
